### PR TITLE
Run API check to assert xfrm modules

### LINKED ISSUE #1439: encrypted overlay is not compatible with CONFIG_XFRM_ALGO and CONFIG_XFRM_USER kernel options compiled-in
I'm getting error of missing IPSEC kernel modules on the system where such kernel options are statically compiled.

Steps to reproduce:

1. Get Linux kernel with options CONFIG_XFRM_ALGO and CONFIG_XFRM_USER compiled in (such as boot2docker.iso v1.12.1)
1. Run Docker Engine 1.12.1 in swarm mode on it
1. Create encrypted overlay network
1. Attempt to schedule service container on it

Expected result: container starts just fine

Actual result:
- Container fails to start: `cannot join secure network: required modules to install IPSEC rules are missing on host`
- Warning in docker.log: ```Could not load necessary modules for IPSEC rules: Running modprobe xfrm_user failed with message: `modprobe: module xfrm_user not found in modules.dep` ```

Seems like #1281 implemented an unconditional modprobe for xfrm_user and xfrm_algo.
This leads to false reports of lack of IPSEC kernel support on systems which had those modules compiled in.

### PR DESCRIPTION
**Pull request by aboch**
- When docker is run inside a container, the infrastructure
  needed by modprobe is not always available, causing the
  xfrm module load to fail even when these modules are already
  loaded or builtin in the kernel.
- In case of probe failure, before declaring the failure,
  run an API check by attempting the creation of
  a NETLINK_XFRM socket.

Fixes  #1439 
Related to https://github.com/docker/docker/issues/27188

Signed-off-by: Alessandro Boch <aboch@docker.com>

### CODE REVIEW

File: ns/init_linux.go [hunk 1]
```diff
@@ -76,11 +76,28 @@ func getSupportedNlFamilies() []int {
...
-	if out, err := exec.Command("modprobe", "-va", "xfrm_algo").CombinedOutput(); err != nil {
-		return fmt.Errorf("Running modprobe xfrm_algo failed with message: `%s`, error: %v", strings.TrimSpace(string(out)), err)
+	if err := loadModule("xfrm_algo"); err != nil {
+		return err
 	}
 	return nil
 }
+
+func loadModule(module string) error {
+	if !isModuleAlive(module) {
```
Comment (mrjana) [inline ns/init_linux.go]: Is this based on the assumption that the module is already loaded in the host before you started the daemon inside dind? Because of the module is not loaded you for sure cannot try to load it inside dind unless you bind mount certain host directories.

Comment (aboch) [inline ns/init_linux.go]: This is for avoiding to modprobe when we know from `/proc/modules` that the module is already there. Given we know there are cases when running inside a container where modprobe would fail for reasons not related to the bring up of the module.
This is expecially true when running docker daemon inside a container.

**Comment by aboch** [comment]
Discussed this offline with @mrjana.
He is suggesting to instead run an API check, because this is the most future proof approach.
I agree with that and will make the change.

File: ns/init_linux.go [hunk 2]
```diff
@@ -68,19 +66,19 @@ func NlHandle() *netlink.Handle {
 
 func getSupportedNlFamilies() []int {
 	fams := []int{syscall.NETLINK_ROUTE}
-	if err := loadXfrmModules(); err != nil {
-		log.Warnf("Could not load necessary modules for IPSEC rules: %v", err)
+	if err := checkXfrmSocket(); err != nil {
+		log.Warnf("Required socket to program IPSEC rules cannot be created: %v. (Requires xfrm_user and xfrm_ago modules)", err)
```
Comment (mrjana) [inline ns/init_linux.go]: Uhm.. You still need to try loading xfrm modules in case the `checkXfrmSocket` fails. This is for cases where the module doesn't get autoloaded.

**Comment by aboch** [comment]
@mrjana Tokk care of your comments.
PTAL when yo uget a chance

**Comment by mavenugo** [comment]
LGTM

**Comment by justincormack** [comment]
Normally modules autoload anyway when you try to use the symbols, so I don't think it is even necessary to try to modprobe on fallback, but this is certainly an improvement.
