### PR TITLE
write to /proc/sys/net/ipv4/ip_forward only if is not already enabled

### LINKED ISSUE #405: Setup IP forwarding fails when /proc/sys is RO, even if ip_forward is already 1
Setup IP forwarding fails when `/proc/sys` is mounted as read-only (for example inside LXC container), even if `/proc/sys/net/ipv4/ip_forward` is already set to 1

Maybe it would be good to check value of  `/proc/sys/net/ipv4/ip_forward` and if it is already set to 1, then leave it alone.

### PR DESCRIPTION
**Pull request by kadel**
fixes #405

Signed-off-by: Tomas Kral <tomas.kral@gmail.com>

### CODE REVIEW

**Comment by aboch** [comment]
@kadel There are several other places where we write to a config file under /proc/sys in bridge driver code. The closest is setup_ipv6.go. WDYT about adding the same `read first` logic there as well ?

BTW, this seems a stop-gap solution where daemon will be able to start in a system with read-only mounted /proc/sys directory but only if the required settings are somehow already enabled.

I am still fine with this best-effort solution, as it does introduce a very legitimate `modify only if needed` logic which cannot be said to have been added to only cover a corner case.

**Comment by kadel** [comment]
good point ;-) I'm going to check for other places where libnetwork writes to /proc/sys and add same logic there as well.

File: drivers/bridge/setup_ipv6.go [hunk 1]
```diff
@@ -70,12 +72,29 @@ func setupGatewayIPv6(config *networkConfiguration, i *bridgeInterface) error {
...
-	// Enable IPv6 forwarding
-	if err := ioutil.WriteFile("/proc/sys/net/ipv6/conf/default/forwarding", []byte{'1', '\n'}, ipv6ForwardConfPerm); err != nil {
-		logrus.Warnf("Unable to enable IPv6 default forwarding: %v", err)
+	// Get current IPv6 default forwarding setup
+	ipv6ForwardDataDefault, err := ioutil.ReadFile(ipv6ForwardConfDefault)
+	if err != nil {
+		return fmt.Errorf("Cannot read IPv6 default forwarding setup: %v", err)
+	}
+	// Enable IPv6 default forwarding only if it is not already enabled
+	if ipv6ForwardDataDefault[0] != '1' {
```
Comment (aboch) [inline drivers/bridge/setup_ipv6.go]: Thanks for taking care of the v6 forwarding case as well.
If IPv6 enabled flag is passed, also call at line 32 in this file would fail. Can you please take care of that as well.

Comment (kadel) [inline drivers/bridge/setup_ipv6.go]: Thanks for quick feedback.
I updated commit.

File: drivers/bridge/setup_ipv4.go [hunk 2]
```diff
@@ -120,10 +120,16 @@ func setupGatewayIPv4(config *networkConfiguration, i *bridgeInterface) error {
 }
 
 func setupLoopbackAdressesRouting(config *networkConfiguration, i *bridgeInterface) error {
-	// Enable loopback adresses routing
 	sysPath := filepath.Join("/proc/sys/net/ipv4/conf", config.BridgeName, "route_localnet")
-	if err := ioutil.WriteFile(sysPath, []byte{'1', '\n'}, 0644); err != nil {
-		return fmt.Errorf("Unable to enable local routing for hairpin mode: %v", err)
+	ipv4LoRoutingData, err := ioutil.ReadFile(sysPath)
+	if err != nil {
+		return fmt.Errorf("Cannot read IPv6 all forwarding setup: %v", err)
```
Comment (aboch) [inline drivers/bridge/setup_ipv4.go]: Please put the appropriate error msg

Comment (kadel) [inline drivers/bridge/setup_ipv4.go]: aj  :blush:

**Comment by aboch** [comment]
LGTM

**Comment by sanimej** [comment]
LGTM

**Comment by aboch** [comment]
@kadel Can you please rebase

**Comment by kadel** [comment]
@aboch  done ;-)
