### PR TITLE
Remove unwanted lock

### LINKED ISSUE #545: [REGRESSION] docker hangs when running containers with routes defined.
I'm trying to get the calico plugin updated with the latest API changes. 

When I try to run a container, docker hangs
```
docker-1.9.0-dev run -tid --publish-service srv$RANDOM.net6.calico busybox
```

Stack trace generated with `sudo pkill -e -SIGQUIT docker`
```
INFO[0023] Processing signal 'quit'                     
INFO[0023] === BEGIN goroutine stack dump ===
goroutine 132 [running]:
github.com/docker/docker/pkg/signal.DumpStacks()
	/go/src/github.com/docker/docker/pkg/signal/trap.go:67 +0xa5
github.com/docker/docker/pkg/signal.func·001(0x7fa745f070e8, 0xc2086be528)
	/go/src/github.com/docker/docker/pkg/signal/trap.go:48 +0x35e
created by github.com/docker/docker/pkg/signal.func·002
	/go/src/github.com/docker/docker/pkg/signal/trap.go:53 +0x13a

goroutine 1 [chan receive]:
main.(*DaemonCli).CmdDaemon(0xc20809a530, 0xc20809ac10, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/docker/daemon.go:290 +0x17d8
main.handleGlobalDaemonFlag()
	/go/src/github.com/docker/docker/docker/daemon.go:65 +0x22c
main.main()
	/go/src/github.com/docker/docker/docker/docker.go:55 +0x2e5

goroutine 5 [runnable]:
sync.(*Mutex).Unlock(0x19b3f40)
	/usr/local/go/src/sync/mutex.go:82
os/signal.process(0x7fa745f070e8, 0xc2086be528)
	/usr/local/go/src/os/signal/signal.go:131 +0x19d
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x71
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 11 [chan receive]:
github.com/docker/docker/daemon.func·028()
	/go/src/github.com/docker/docker/daemon/debugtrap_unix.go:17 +0x5c
created by github.com/docker/docker/daemon.setupDumpStackTrap
	/go/src/github.com/docker/docker/daemon/debugtrap_unix.go:20 +0x18e

goroutine 10 [chan receive]:
github.com/docker/docker/api/server.(*Server).ServeAPI(0xc208032ec0, 0xc20809ad90, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/server.go:99 +0x74f
main.func·007()
	/go/src/github.com/docker/docker/docker/daemon.go:240 +0x5b
created by main.(*DaemonCli).CmdDaemon
	/go/src/github.com/docker/docker/docker/daemon.go:246 +0xd0b

goroutine 12 [IO wait]:
net.(*pollDesc).Wait(0xc2081f61b0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2081f61b0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc2081f6150, 0x0, 0x7fa745f0b380, 0xc208482b08)
	/usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*UnixListener).AcceptUnix(0xc208285140, 0xc20832c680, 0x0, 0x0)
	/usr/local/go/src/net/unixsock_posix.go:282 +0x56
net.(*UnixListener).Accept(0xc208285140, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/unixsock_posix.go:293 +0x4c
github.com/docker/docker/pkg/listenbuffer.(*defaultListener).Accept(0xc208285160, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/pkg/listenbuffer/buffer.go:71 +0x67
net/http.(*Server).Serve(0xc2081ba360, 0x7fa745f13648, 0xc208285160, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1728 +0x92
github.com/docker/docker/api/server.(*HTTPServer).Serve(0xc2082853e0, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/server.go:118 +0x4d
github.com/docker/docker/api/server.func·007(0x7fa745f136a8, 0xc2082853e0)
	/go/src/github.com/docker/docker/api/server/server.go:90 +0x40
created by github.com/docker/docker/api/server.(*Server).ServeAPI
	/go/src/github.com/docker/docker/api/server/server.go:94 +0x6ac

goroutine 14 [IO wait]:
net.(*pollDesc).Wait(0xc20818f5d0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20818f5d0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).readMsg(0xc20818f570, 0xc20809a620, 0x10, 0x10, 0xc208321220, 0x1000, 0x1000, 0xffffffffffffffff, 0x0, 0x0, ...)
	/usr/local/go/src/net/fd_unix.go:296 +0x54e
net.(*UnixConn).ReadMsgUnix(0xc208036608, 0xc20809a620, 0x10, 0x10, 0xc208321220, 0x1000, 0x1000, 0x51, 0xc2080e8f14, 0x4, ...)
	/usr/local/go/src/net/unixsock_posix.go:147 +0x167
github.com/godbus/dbus.(*oobReader).Read(0xc208321200, 0xc20809a620, 0x10, 0x10, 0xc208321200, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/godbus/dbus/transport_unix.go:21 +0xc5
io.ReadAtLeast(0x7fa745f14490, 0xc208321200, 0xc20809a620, 0x10, 0x10, 0x10, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:298 +0xf1
io.ReadFull(0x7fa745f14490, 0xc208321200, 0xc20809a620, 0x10, 0x10, 0x51, 0x0, 0x0)
	/usr/local/go/src/io/io.go:316 +0x6d
github.com/godbus/dbus.(*unixTransport).ReadMessage(0xc208154c30, 0xc20830c120, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/godbus/dbus/transport_unix.go:85 +0x1bf
github.com/godbus/dbus.(*Conn).inWorker(0xc2083087e0)
	/go/src/github.com/docker/docker/vendor/src/github.com/godbus/dbus/conn.go:248 +0x58
created by github.com/godbus/dbus.(*Conn).Auth
	/go/src/github.com/docker/docker/vendor/src/github.com/godbus/dbus/auth.go:118 +0xe84

goroutine 15 [chan receive]:
github.com/godbus/dbus.(*Conn).outWorker(0xc2083087e0)
	/go/src/github.com/docker/docker/vendor/src/github.com/godbus/dbus/conn.go:370 +0x58
created by github.com/godbus/dbus.(*Conn).Auth
	/go/src/github.com/docker/docker/vendor/src/github.com/godbus/dbus/auth.go:119 +0xea1

goroutine 16 [chan receive]:
github.com/docker/libnetwork/iptables.signalHandler()
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/iptables/firewalld.go:92 +0x57
created by github.com/docker/libnetwork/iptables.FirewalldInit
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/iptables/firewalld.go:48 +0x185

goroutine 25 [IO wait]:
net.(*pollDesc).Wait(0xc208158140, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208158140, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc2081580e0, 0x0, 0x7fa745f0b380, 0xc2081e7238)
	/usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*UnixListener).AcceptUnix(0xc20832d740, 0x10, 0x0, 0x0)
	/usr/local/go/src/net/unixsock_posix.go:282 +0x56
net.(*UnixListener).Accept(0xc20832d740, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/unixsock_posix.go:293 +0x4c
github.com/docker/libnetwork.(*controller).acceptClientConnections(0xc2082bbec0, 0xc208158070, 0x63, 0x7fa745f13610, 0xc20832d740)
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/sandbox_externalkey.go:138 +0x87
created by github.com/docker/libnetwork.(*controller).startExternalKeyListener
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/sandbox_externalkey.go:132 +0x28f

goroutine 41 [chan receive]:
database/sql.(*DB).connectionOpener(0xc2081a0640)
	/usr/local/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:452 +0x31c

goroutine 45 [chan receive]:
github.com/godbus/dbus.(*Conn).outWorker(0xc208316360)
	/go/src/github.com/docker/docker/vendor/src/github.com/godbus/dbus/conn.go:370 +0x58
created by github.com/godbus/dbus.(*Conn).Auth
	/go/src/github.com/docker/docker/vendor/src/github.com/godbus/dbus/auth.go:119 +0xea1

goroutine 44 [IO wait]:
net.(*pollDesc).Wait(0xc20818fdb0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20818fdb0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).readMsg(0xc20818fd50, 0xc2081822f0, 0x10, 0x10, 0xc20832a820, 0x1000, 0x1000, 0xffffffffffffffff, 0x0, 0x0, ...)
	/usr/local/go/src/net/fd_unix.go:296 +0x54e
net.(*UnixConn).ReadMsgUnix(0xc208036b58, 0xc2081822f0, 0x10, 0x10, 0xc20832a820, 0x1000, 0x1000, 0x27, 0xc2081adf54, 0x4, ...)
	/usr/local/go/src/net/unixsock_posix.go:147 +0x167
github.com/godbus/dbus.(*oobReader).Read(0xc20832a800, 0xc2081822f0, 0x10, 0x10, 0xc20832a800, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/godbus/dbus/transport_unix.go:21 +0xc5
io.ReadAtLeast(0x7fa745f14490, 0xc20832a800, 0xc2081822f0, 0x10, 0x10, 0x10, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:298 +0xf1
io.ReadFull(0x7fa745f14490, 0xc20832a800, 0xc2081822f0, 0x10, 0x10, 0x27, 0x0, 0x0)
	/usr/local/go/src/io/io.go:316 +0x6d
github.com/godbus/dbus.(*unixTransport).ReadMessage(0xc2081821a0, 0xc208190780, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/godbus/dbus/transport_unix.go:85 +0x1bf
github.com/godbus/dbus.(*Conn).inWorker(0xc208316360)
	/go/src/github.com/docker/docker/vendor/src/github.com/godbus/dbus/conn.go:248 +0x58
created by github.com/godbus/dbus.(*Conn).Auth
	/go/src/github.com/docker/docker/vendor/src/github.com/godbus/dbus/auth.go:118 +0xe84

goroutine 46 [IO wait]:
net.(*pollDesc).Wait(0xc2081f67d0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2081f67d0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).readMsg(0xc2081f6770, 0xc2086be270, 0x10, 0x10, 0xc2082e1220, 0x1000, 0x1000, 0xffffffffffffffff, 0x0, 0x0, ...)
	/usr/local/go/src/net/fd_unix.go:296 +0x54e
net.(*UnixConn).ReadMsgUnix(0xc208036b68, 0xc2086be270, 0x10, 0x10, 0xc2082e1220, 0x1000, 0x1000, 0x59, 0xc2086aff74, 0x4, ...)
	/usr/local/go/src/net/unixsock_posix.go:147 +0x167
github.com/godbus/dbus.(*oobReader).Read(0xc2082e1200, 0xc2086be270, 0x10, 0x10, 0xc2082e1200, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/godbus/dbus/transport_unix.go:21 +0xc5
io.ReadAtLeast(0x7fa745f14490, 0xc2082e1200, 0xc2086be270, 0x10, 0x10, 0x10, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:298 +0xf1
io.ReadFull(0x7fa745f14490, 0xc2082e1200, 0xc2086be270, 0x10, 0x10, 0x59, 0x0, 0x0)
	/usr/local/go/src/io/io.go:316 +0x6d
github.com/godbus/dbus.(*unixTransport).ReadMessage(0xc208183960, 0xc20830f860, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/godbus/dbus/transport_unix.go:85 +0x1bf
github.com/godbus/dbus.(*Conn).inWorker(0xc2083167e0)
	/go/src/github.com/docker/docker/vendor/src/github.com/godbus/dbus/conn.go:248 +0x58
created by github.com/godbus/dbus.(*Conn).Auth
	/go/src/github.com/docker/docker/vendor/src/github.com/godbus/dbus/auth.go:118 +0xe84

goroutine 47 [chan receive]:
github.com/godbus/dbus.(*Conn).outWorker(0xc2083167e0)
	/go/src/github.com/docker/docker/vendor/src/github.com/godbus/dbus/conn.go:370 +0x58
created by github.com/godbus/dbus.(*Conn).Auth
	/go/src/github.com/docker/docker/vendor/src/github.com/godbus/dbus/auth.go:119 +0xea1

goroutine 48 [chan receive]:
github.com/coreos/go-systemd/dbus.func·001()
	/go/src/github.com/docker/docker/vendor/src/github.com/coreos/go-systemd/dbus/subscription.go:64 +0x64
created by github.com/coreos/go-systemd/dbus.(*Conn).dispatch
	/go/src/github.com/docker/docker/vendor/src/github.com/coreos/go-systemd/dbus/subscription.go:96 +0x11d

goroutine 49 [chan receive]:
github.com/docker/docker/daemon.(*statsCollector).run(0xc20830de60)
	/go/src/github.com/docker/docker/daemon/stats_collector_unix.go:91 +0xb2
created by github.com/docker/docker/daemon.newStatsCollector
	/go/src/github.com/docker/docker/daemon/stats_collector_unix.go:31 +0x116

goroutine 50 [chan receive]:
github.com/docker/docker/daemon.(*Daemon).execCommandGC(0xc20819a000)
	/go/src/github.com/docker/docker/daemon/exec.go:290 +0x8c
created by github.com/docker/docker/daemon.NewDaemon
	/go/src/github.com/docker/docker/daemon/daemon.go:768 +0x275d

goroutine 126 [syscall]:
syscall.Syscall(0x0, 0x1d, 0xc208016f50, 0x8, 0x0, 0x0, 0xc208482580)
	/usr/local/go/src/syscall/asm_linux_amd64.s:21 +0x5
syscall.read(0x1d, 0xc208016f50, 0x8, 0x8, 0xe1da80, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:867 +0x6e
syscall.Read(0x1d, 0xc208016f50, 0x8, 0x8, 0xc208016eb8, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_unix.go:136 +0x58
os.(*File).read(0xc20860a918, 0xc208016f50, 0x8, 0x8, 0xc2082a8000, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:191 +0x5e
os.(*File).Read(0xc20860a918, 0xc208016f50, 0x8, 0x8, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/file.go:95 +0x91
github.com/opencontainers/runc/libcontainer.func·009()
	/go/src/github.com/docker/docker/vendor/src/github.com/opencontainers/runc/libcontainer/notify_linux.go:51 +0x18c
created by github.com/opencontainers/runc/libcontainer.notifyOnOOM
	/go/src/github.com/docker/docker/vendor/src/github.com/opencontainers/runc/libcontainer/notify_linux.go:61 +0x887

goroutine 125 [syscall]:
syscall.Syscall(0x0, 0x21, 0xc2085de000, 0x8000, 0x0, 0x8000, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:21 +0x5
syscall.read(0x21, 0xc2085de000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:867 +0x6e
syscall.Read(0x21, 0xc2085de000, 0x8000, 0x8000, 0x1c, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_unix.go:136 +0x58
os.(*File).read(0xc20860a6e0, 0xc2085de000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:191 +0x5e
os.(*File).Read(0xc20860a6e0, 0xc2085de000, 0x8000, 0x8000, 0x1c, 0x0, 0x0)
	/usr/local/go/src/os/file.go:95 +0x91
io.Copy(0x7fa745f243e8, 0xc2081c3de0, 0x7fa745f0b330, 0xc20860a6e0, 0x55, 0x0, 0x0)
	/usr/local/go/src/io/io.go:362 +0x1f6
os/exec.func·003(0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:221 +0x7d
os/exec.func·004(0xc2082120e0)
	/usr/local/go/src/os/exec/exec.go:328 +0x2d
created by os/exec.(*Cmd).Start
	/usr/local/go/src/os/exec/exec.go:329 +0xb6d

goroutine 124 [syscall]:
syscall.Syscall(0x0, 0x1f, 0xc2083e4000, 0x8000, 0x0, 0x8000, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:21 +0x5
syscall.read(0x1f, 0xc2083e4000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:867 +0x6e
syscall.Read(0x1f, 0xc2083e4000, 0x8000, 0x8000, 0x6e, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_unix.go:136 +0x58
os.(*File).read(0xc20860a6c0, 0xc2083e4000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:191 +0x5e
os.(*File).Read(0xc20860a6c0, 0xc2083e4000, 0x8000, 0x8000, 0x6e, 0x0, 0x0)
	/usr/local/go/src/os/file.go:95 +0x91
io.Copy(0x7fa745f243e8, 0xc2081c3e00, 0x7fa745f0b330, 0xc20860a6c0, 0x43e, 0x0, 0x0)
	/usr/local/go/src/io/io.go:362 +0x1f6
os/exec.func·003(0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:221 +0x7d
os/exec.func·004(0xc2082120a0)
	/usr/local/go/src/os/exec/exec.go:328 +0x2d
created by os/exec.(*Cmd).Start
	/usr/local/go/src/os/exec/exec.go:329 +0xb6d

goroutine 123 [semacquire]:
sync.(*Cond).Wait(0xc2083b6e70)
	/usr/local/go/src/sync/cond.go:62 +0x9e
github.com/docker/docker/pkg/ioutils.(*bufReader).Read(0xc2083b6e40, 0xc2083e3000, 0x1000, 0x1000, 0x0, 0x7fa745f070c0, 0xc2080280d0)
	/go/src/github.com/docker/docker/pkg/ioutils/readers.go:213 +0x158
bufio.(*Reader).fill(0xc20839b440)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc20839b440, 0x6d800a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:295 +0x257
bufio.(*Reader).ReadBytes(0xc20839b440, 0xc2086a2b0a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:374 +0xd2
github.com/docker/docker/daemon/logger.(*Copier).copySrc(0xc20828b080, 0x11877c0, 0x6, 0x7fa745f243c0, 0xc2083b6e40)
	/go/src/github.com/docker/docker/daemon/logger/copier.go:47 +0x96
created by github.com/docker/docker/daemon/logger.(*Copier).Run
	/go/src/github.com/docker/docker/daemon/logger/copier.go:38 +0x11c

goroutine 122 [semacquire]:
sync.(*Cond).Wait(0xc2083b6cf0)
	/usr/local/go/src/sync/cond.go:62 +0x9e
github.com/docker/docker/pkg/ioutils.(*bufReader).Read(0xc2083b6cc0, 0xc2083e2000, 0x1000, 0x1000, 0x0, 0x7fa745f070c0, 0xc2080280d0)
	/go/src/github.com/docker/docker/pkg/ioutils/readers.go:213 +0x158
bufio.(*Reader).fill(0xc20839b380)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc20839b380, 0x6d800a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:295 +0x257
bufio.(*Reader).ReadBytes(0xc20839b380, 0xc2086a2b0a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:374 +0xd2
github.com/docker/docker/daemon/logger.(*Copier).copySrc(0xc20828b080, 0x1187800, 0x6, 0x7fa745f243c0, 0xc2083b6cc0)
	/go/src/github.com/docker/docker/daemon/logger/copier.go:47 +0x96
created by github.com/docker/docker/daemon/logger.(*Copier).Run
	/go/src/github.com/docker/docker/daemon/logger/copier.go:38 +0x11c

goroutine 121 [semacquire]:
sync.(*Cond).Wait(0xc2083b6db0)
	/usr/local/go/src/sync/cond.go:62 +0x9e
io.(*pipe).read(0xc2083b6d80, 0xc2083b2800, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/pipe.go:52 +0x303
io.(*PipeReader).Read(0xc20860a3f0, 0xc2083b2800, 0x400, 0x400, 0x1c, 0x0, 0x0)
	/usr/local/go/src/io/pipe.go:134 +0x5b
github.com/docker/docker/pkg/ioutils.(*bufReader).drain(0xc2083b6e40)
	/go/src/github.com/docker/docker/pkg/ioutils/readers.go:119 +0x10e
created by github.com/docker/docker/pkg/ioutils.NewBufReader
	/go/src/github.com/docker/docker/pkg/ioutils/readers.go:88 +0x324

goroutine 120 [semacquire]:
sync.(*Cond).Wait(0xc2083b6c30)
	/usr/local/go/src/sync/cond.go:62 +0x9e
io.(*pipe).read(0xc2083b6c00, 0xc2083b2400, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/pipe.go:52 +0x303
io.(*PipeReader).Read(0xc20860a3e0, 0xc2083b2400, 0x400, 0x400, 0x6e, 0x0, 0x0)
	/usr/local/go/src/io/pipe.go:134 +0x5b
github.com/docker/docker/pkg/ioutils.(*bufReader).drain(0xc2083b6cc0)
	/go/src/github.com/docker/docker/pkg/ioutils/readers.go:119 +0x10e
created by github.com/docker/docker/pkg/ioutils.NewBufReader
	/go/src/github.com/docker/docker/pkg/ioutils/readers.go:88 +0x324

goroutine 119 [syscall]:
syscall.Syscall6(0x3d, 0x40b6, 0xc20825f41c, 0x0, 0xc208658240, 0x0, 0x0, 0x4cc16c, 0x4cc5f2, 0xfba9c0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:46 +0x5
syscall.wait4(0x40b6, 0xc20825f41c, 0x0, 0xc208658240, 0x90, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:124 +0x79
syscall.Wait4(0x40b6, 0xc20825f464, 0x0, 0xc208658240, 0x4a4d3b, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_linux.go:224 +0x60
os.(*Process).wait(0xc2082121e0, 0xc2082ba200, 0x0, 0x0)
	/usr/local/go/src/os/exec_unix.go:22 +0x103
os.(*Process).Wait(0xc2082121e0, 0xc20825f528, 0x0, 0x0)
	/usr/local/go/src/os/doc.go:45 +0x3a
os/exec.(*Cmd).Wait(0xc20838f180, 0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:364 +0x23c
github.com/opencontainers/runc/libcontainer.(*initProcess).wait(0xc2085f4ff0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/opencontainers/runc/libcontainer/process_linux.go:235 +0x3d
github.com/opencontainers/runc/libcontainer.Process.Wait(0xc2081ac320, 0x1, 0x1, 0xc2085ec280, 0x8, 0x8, 0x19c53b8, 0x0, 0x19c53b8, 0x0, ...)
	/go/src/github.com/docker/docker/vendor/src/github.com/opencontainers/runc/libcontainer/process.go:60 +0x11d
github.com/opencontainers/runc/libcontainer.Process.Wait·fm(0xc20825fa00, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/execdriver/native/driver.go:179 +0x58
github.com/docker/docker/daemon/execdriver/native.(*Driver).Run(0xc2082f2820, 0xc208216380, 0xc2083f7500, 0xc20860a408, 0x1, 0x1, 0xc2082355b0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/docker/daemon/execdriver/native/driver.go:185 +0xa1f
github.com/docker/docker/daemon.(*Daemon).run(0xc20819a000, 0xc2082312c0, 0xc2083f7500, 0xc2082355b0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/daemon.go:887 +0x246
github.com/docker/docker/daemon.(*containerMonitor).Start(0xc20820c620, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/monitor.go:145 +0x484
github.com/docker/docker/daemon.*containerMonitor.Start·fm(0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/container.go:751 +0x39
github.com/docker/docker/pkg/promise.func·001()
	/go/src/github.com/docker/docker/pkg/promise/promise.go:8 +0x2f
created by github.com/docker/docker/pkg/promise.Go
	/go/src/github.com/docker/docker/pkg/promise/promise.go:9 +0xfb

goroutine 127 [semacquire]:
sync.(*Mutex).Lock(0xc2086a9dbc)
	/usr/local/go/src/sync/mutex.go:66 +0xd3
github.com/docker/libnetwork.(*endpoint).addInterfaceRoute(0xc2086a9d40, 0xc2086b3680, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/endpoint_info.go:214 +0x56
github.com/docker/libnetwork.(*endpoint).AddStaticRoute(0xc2086a9d40, 0xc2086b3650, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/endpoint_info.go:206 +0x296
github.com/docker/libnetwork/drivers/remote.(*driver).Join(0xc2082445a0, 0xc208683500, 0x40, 0xc208683b00, 0x40, 0xc2086b2c90, 0x22, 0x7fa745f24298, 0xc2086a9d40, 0xc2086b2990, ...)
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/drivers/remote/driver.go:229 +0xd48
github.com/docker/libnetwork.(*endpoint).Join(0xc2086a9d40, 0x7fa745f24238, 0xc208069680, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/endpoint.go:259 +0x5a7
github.com/docker/docker/daemon.(*Container).configureNetwork(0xc20823fe00, 0xc20832c9e9, 0x4, 0xc20832c9e0, 0x8, 0xc20832c9ee, 0x6, 0x1, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/container_unix.go:918 +0x629
github.com/docker/docker/daemon.(*Container).allocateNetwork(0xc20823fe00, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/container_unix.go:855 +0x587
github.com/docker/docker/daemon.(*Container).initializeNetworking(0xc20823fe00, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/container_unix.go:960 +0x4c6
github.com/docker/docker/daemon.(*Container).Start(0xc20823fe00, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/container.go:276 +0x233
github.com/docker/docker/daemon.(*Daemon).ContainerStart(0xc20819a000, 0xc20810a167, 0x40, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/start.go:47 +0x24f
github.com/docker/docker/api/server.(*Server).postContainersStart(0xc208032ec0, 0x7fa745f1ac08, 0xc2086933b0, 0x7fa745f1ab90, 0xc2083855e0, 0xc2085b7450, 0xc208693290, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/container.go:182 +0x162
github.com/docker/docker/api/server.*Server.(github.com/docker/docker/api/server.postContainersStart)·fm(0x7fa745f1ac08, 0xc2086933b0, 0x7fa745f1ab90, 0xc2083855e0, 0xc2085b7450, 0xc208693290, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/server.go:406 +0x78
github.com/docker/docker/api/server.func·008(0x7fa745f1ab90, 0xc2083855e0, 0xc2085b7450)
	/go/src/github.com/docker/docker/api/server/server.go:352 +0xf5c
net/http.HandlerFunc.ServeHTTP(0xc20809e7c0, 0x7fa745f1ab90, 0xc2083855e0, 0xc2085b7450)
	/usr/local/go/src/net/http/server.go:1265 +0x41
github.com/gorilla/mux.(*Router).ServeHTTP(0xc208056a50, 0x7fa745f1ab90, 0xc2083855e0, 0xc2085b7450)
	/go/src/github.com/docker/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x297
net/http.serverHandler.ServeHTTP(0xc2081ba360, 0x7fa745f1ab90, 0xc2083855e0, 0xc2085b7450)
	/usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208384be0)
	/usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e

goroutine 113 [syscall]:
syscall.Syscall(0x0, 0x14, 0xc208015750, 0x8, 0x0, 0x0, 0xc2082ae7a0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:21 +0x5
syscall.read(0x14, 0xc208015750, 0x8, 0x8, 0xe1da80, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:867 +0x6e
syscall.Read(0x14, 0xc208015750, 0x8, 0x8, 0xc2080156b8, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_unix.go:136 +0x58
os.(*File).read(0xc20860af48, 0xc208015750, 0x8, 0x8, 0xc2082a8a80, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:191 +0x5e
os.(*File).Read(0xc20860af48, 0xc208015750, 0x8, 0x8, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/file.go:95 +0x91
github.com/opencontainers/runc/libcontainer.func·009()
	/go/src/github.com/docker/docker/vendor/src/github.com/opencontainers/runc/libcontainer/notify_linux.go:51 +0x18c
created by github.com/opencontainers/runc/libcontainer.notifyOnOOM
	/go/src/github.com/docker/docker/vendor/src/github.com/opencontainers/runc/libcontainer/notify_linux.go:61 +0x887

goroutine 112 [syscall]:
syscall.Syscall(0x0, 0x18, 0xc208218000, 0x8000, 0x0, 0x8000, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:21 +0x5
syscall.read(0x18, 0xc208218000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:867 +0x6e
syscall.Read(0x18, 0xc208218000, 0x8000, 0x8000, 0x92, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_unix.go:136 +0x58
os.(*File).read(0xc20860a618, 0xc208218000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:191 +0x5e
os.(*File).Read(0xc20860a618, 0xc208218000, 0x8000, 0x8000, 0x92, 0x0, 0x0)
	/usr/local/go/src/os/file.go:95 +0x91
io.Copy(0x7fa745f243e8, 0xc2085d3f80, 0x7fa745f0b330, 0xc20860a618, 0x855, 0x0, 0x0)
	/usr/local/go/src/io/io.go:362 +0x1f6
os/exec.func·003(0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:221 +0x7d
os/exec.func·004(0xc2083476c0)
	/usr/local/go/src/os/exec/exec.go:328 +0x2d
created by os/exec.(*Cmd).Start
	/usr/local/go/src/os/exec/exec.go:329 +0xb6d

goroutine 93 [chan receive]:
github.com/docker/docker/pkg/signal.func·002()
	/go/src/github.com/docker/docker/pkg/signal/trap.go:29 +0x8f
created by github.com/docker/docker/pkg/signal.Trap
	/go/src/github.com/docker/docker/pkg/signal/trap.go:55 +0x250

goroutine 111 [syscall]:
syscall.Syscall(0x0, 0x16, 0xc2085ba000, 0x8000, 0x1, 0x8000, 0x4a3ecf)
	/usr/local/go/src/syscall/asm_linux_amd64.s:21 +0x5
syscall.read(0x16, 0xc2085ba000, 0x8000, 0x8000, 0x19c5360, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:867 +0x6e
syscall.Read(0x16, 0xc2085ba000, 0x8000, 0x8000, 0xe58140, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_unix.go:136 +0x58
os.(*File).read(0xc20860a5f8, 0xc2085ba000, 0x8000, 0x8000, 0xc2085ba000, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:191 +0x5e
os.(*File).Read(0xc20860a5f8, 0xc2085ba000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
	/usr/local/go/src/os/file.go:95 +0x91
io.Copy(0x7fa745f243e8, 0xc2085d3fa0, 0x7fa745f0b330, 0xc20860a5f8, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:362 +0x1f6
os/exec.func·003(0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:221 +0x7d
os/exec.func·004(0xc208347660)
	/usr/local/go/src/os/exec/exec.go:328 +0x2d
created by os/exec.(*Cmd).Start
	/usr/local/go/src/os/exec/exec.go:329 +0xb6d

goroutine 110 [semacquire]:
sync.(*Cond).Wait(0xc2083b69f0)
	/usr/local/go/src/sync/cond.go:62 +0x9e
github.com/docker/docker/pkg/ioutils.(*bufReader).Read(0xc2083b69c0, 0xc2085b8000, 0x1000, 0x1000, 0x0, 0x7fa745f070c0, 0xc2080280d0)
	/go/src/github.com/docker/docker/pkg/ioutils/readers.go:213 +0x158
bufio.(*Reader).fill(0xc20829d740)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc20829d740, 0x6d800a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:295 +0x257
bufio.(*Reader).ReadBytes(0xc20829d740, 0xc20824200a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:374 +0xd2
github.com/docker/docker/daemon/logger.(*Copier).copySrc(0xc20827f4c0, 0x11877c0, 0x6, 0x7fa745f243c0, 0xc2083b69c0)
	/go/src/github.com/docker/docker/daemon/logger/copier.go:47 +0x96
created by github.com/docker/docker/daemon/logger.(*Copier).Run
	/go/src/github.com/docker/docker/daemon/logger/copier.go:38 +0x11c

goroutine 109 [semacquire]:
sync.(*Cond).Wait(0xc2083b67b0)
	/usr/local/go/src/sync/cond.go:62 +0x9e
github.com/docker/docker/pkg/ioutils.(*bufReader).Read(0xc2083b6780, 0xc2085dd000, 0x1000, 0x1000, 0x0, 0x7fa745f070c0, 0xc2080280d0)
	/go/src/github.com/docker/docker/pkg/ioutils/readers.go:213 +0x158
bufio.(*Reader).fill(0xc20829d5c0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc20829d5c0, 0x4a690a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:295 +0x257
bufio.(*Reader).ReadBytes(0xc20829d5c0, 0xc2083b670a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:374 +0xd2
github.com/docker/docker/daemon/logger.(*Copier).copySrc(0xc20827f4c0, 0x1187800, 0x6, 0x7fa745f243c0, 0xc2083b6780)
	/go/src/github.com/docker/docker/daemon/logger/copier.go:47 +0x96
created by github.com/docker/docker/daemon/logger.(*Copier).Run
	/go/src/github.com/docker/docker/daemon/logger/copier.go:38 +0x11c

goroutine 108 [semacquire]:
sync.(*Cond).Wait(0xc2083b6870)
	/usr/local/go/src/sync/cond.go:62 +0x9e
io.(*pipe).read(0xc2083b6840, 0xc2081fcc00, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/pipe.go:52 +0x303
io.(*PipeReader).Read(0xc20860a558, 0xc2081fcc00, 0x400, 0x400, 0x92, 0x0, 0x0)
	/usr/local/go/src/io/pipe.go:134 +0x5b
github.com/docker/docker/pkg/ioutils.(*bufReader).drain(0xc2083b69c0)
	/go/src/github.com/docker/docker/pkg/ioutils/readers.go:119 +0x10e
created by github.com/docker/docker/pkg/ioutils.NewBufReader
	/go/src/github.com/docker/docker/pkg/ioutils/readers.go:88 +0x324

goroutine 106 [syscall]:
syscall.Syscall6(0x3d, 0x4095, 0xc2083fb41c, 0x0, 0xc2083d3200, 0x0, 0x0, 0x4cc16c, 0x4cc5f2, 0xfba9c0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:46 +0x5
syscall.wait4(0x4095, 0xc2083fb41c, 0x0, 0xc2083d3200, 0x90, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:124 +0x79
syscall.Wait4(0x4095, 0xc2083fb464, 0x0, 0xc2083d3200, 0x4a4cc8, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_linux.go:224 +0x60
os.(*Process).wait(0xc2083477e0, 0xc2081ba8c0, 0x0, 0x0)
	/usr/local/go/src/os/exec_unix.go:22 +0x103
os.(*Process).Wait(0xc2083477e0, 0xc2083fb528, 0x0, 0x0)
	/usr/local/go/src/os/doc.go:45 +0x3a
os/exec.(*Cmd).Wait(0xc20838edc0, 0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:364 +0x23c
github.com/opencontainers/runc/libcontainer.(*initProcess).wait(0xc2082f3040, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/opencontainers/runc/libcontainer/process_linux.go:235 +0x3d
github.com/opencontainers/runc/libcontainer.Process.Wait(0xc2082f2dc0, 0x5, 0x5, 0xc20827f280, 0x3, 0x4, 0x19c53b8, 0x0, 0x19c53b8, 0x0, ...)
	/go/src/github.com/docker/docker/vendor/src/github.com/opencontainers/runc/libcontainer/process.go:60 +0x11d
github.com/opencontainers/runc/libcontainer.Process.Wait·fm(0xc2083fba00, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/execdriver/native/driver.go:179 +0x58
github.com/docker/docker/daemon/execdriver/native.(*Driver).Run(0xc2082f2820, 0xc208217500, 0xc2082db380, 0xc20860a570, 0x1, 0x1, 0xc208270b60, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/docker/daemon/execdriver/native/driver.go:185 +0xa1f
github.com/docker/docker/daemon.(*Daemon).run(0xc20819a000, 0xc2082310e0, 0xc2082db380, 0xc208270b60, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/daemon.go:887 +0x246
github.com/docker/docker/daemon.(*containerMonitor).Start(0xc2081c5a40, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/monitor.go:145 +0x484
github.com/docker/docker/daemon.*containerMonitor.Start·fm(0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/container.go:751 +0x39
github.com/docker/docker/pkg/promise.func·001()
	/go/src/github.com/docker/docker/pkg/promise/promise.go:8 +0x2f
created by github.com/docker/docker/pkg/promise.Go
	/go/src/github.com/docker/docker/pkg/promise/promise.go:9 +0xfb

goroutine 104 [select]:
net.func·019()
	/usr/local/go/src/net/dnsclient_unix.go:241 +0x2f4
created by net.loadConfig
	/usr/local/go/src/net/dnsclient_unix.go:269 +0x20c

goroutine 107 [semacquire]:
sync.(*Cond).Wait(0xc2083b6930)
	/usr/local/go/src/sync/cond.go:62 +0x9e
io.(*pipe).read(0xc2083b6900, 0xc2081fc000, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/pipe.go:52 +0x303
io.(*PipeReader).Read(0xc20860a548, 0xc2081fc000, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/pipe.go:134 +0x5b
github.com/docker/docker/pkg/ioutils.(*bufReader).drain(0xc2083b6780)
	/go/src/github.com/docker/docker/pkg/ioutils/readers.go:119 +0x10e
created by github.com/docker/docker/pkg/ioutils.NewBufReader
	/go/src/github.com/docker/docker/pkg/ioutils/readers.go:88 +0x324

goroutine 105 [select]:
github.com/docker/libnetwork/osl.removeUnusedPaths()
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/osl/namespace_linux.go:73 +0x48b
created by github.com/docker/libnetwork/osl.createBasePath
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/osl/namespace_linux.go:58 +0xb1

=== END goroutine stack dump === 
INFO[0023] Forcing docker daemon shutdown without cleanup on SIGQUIT 

```

The important bit is
```
goroutine 127 [semacquire]:
sync.(*Mutex).Lock(0xc2086a9dbc)
	/usr/local/go/src/sync/mutex.go:66 +0xd3
github.com/docker/libnetwork.(*endpoint).addInterfaceRoute(0xc2086a9d40, 0xc2086b3680, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/endpoint_info.go:214 +0x56
github.com/docker/libnetwork.(*endpoint).AddStaticRoute(0xc2086a9d40, 0xc2086b3650, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/endpoint_info.go:206 +0x296
github.com/docker/libnetwork/drivers/remote.(*driver).Join(0xc2082445a0, 0xc208683500, 0x40, 0xc208683b00, 0x40, 0xc2086b2c90, 0x22, 0x7fa745f24298, 0xc2086a9d40, 0xc2086b2990, ...)
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/drivers/remote/driver.go:229 +0xd48
github.com/docker/libnetwork.(*endpoint).Join(0xc2086a9d40, 0x7fa745f24238, 0xc208069680, 0x0, 0x0, 0x0, 0x0, 0x0)
```

I think the issues was introduced in #508 and in particular, this line https://github.com/docker/libnetwork/pull/508/files#diff-683c78b168c20bf84a33d490085f18aaR214

The `ep` is already locked by the caller, so locking again here causes docker to hang. 

@mrjana  Does that sound right? Can the lock/unlock lines just be removed?

### PR DESCRIPTION
**Pull request by tomdee**
Fixes #545

Signed-off-by: Tom Denham <tom@tomdee.co.uk>

### CODE REVIEW

File: endpoint_info.go [hunk 1]
```diff
@@ -211,9 +211,6 @@ func (ep *endpoint) AddStaticRoute(destination *net.IPNet, routeType int, nextHo
 }
 
 func (ep *endpoint) addInterfaceRoute(route *types.StaticRoute) error {
-	ep.Lock()
-	defer ep.Unlock()
-
```
Comment (aboch) [inline endpoint_info.go]: What about getting rid of this function completely ? It is used only in `AddStaticRoute()` and can be done in one line of code.

Comment (mrjana) [inline endpoint_info.go]: +1. I think it causes unnecessary confusion over when to lock and when not to lock

Comment (aboch) [inline endpoint_info.go]: Too late...

Comment (tomdee) [inline endpoint_info.go]: OK, done.

**Comment by aboch** [comment]
LGTM

**Comment by mrjana** [comment]
LGTM
