### PR TITLE
Fix bitsequence set()

### LINKED ISSUE #495: Cannot start a new container after commit 288275ab60c049fa644f1ce5d36c0c005e8dd02c
# Problem

Starting a new container I get the following reported from the CLI

```
$ docker run -it --rm ubuntu:latest /bin/sh
Error response from daemon: Cannot start container 594872de26b8893a80217e96d3c1891c47c37b5736886d13b2ce4993acf7c438: failed to allocate vxlan id: unexected database index change
```

Logs show the following
```
INFO[2542] POST /v1.19/containers/594872de26b8893a80217e96d3c1891c47c37b5736886d13b2ce4993acf7c438/start 
ERRO[2542] Handler for POST /containers/{name:.*}/start returned error: Cannot start container 594872de26b8893a80217e96d3c1891c47c37b5736886d13b2ce4993acf7c438: failed to allocate vxlan id: unexected database index change 
ERRO[2542] HTTP Error                                    err=Cannot start container 594872de26b8893a80217e96d3c1891c47c37b5736886d13b2ce4993acf7c438: failed to allocate vxlan id: unexected database index change statusCod
e=500
```

# Reproduce
Docker started with the following
```
 /usr/bin/docker daemon -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver aufs --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label com.docker.network.driver.overlay.bind_interface=eth0 --label provider=amazonec2 --default-network=overlay:multihost --kv-store=consul:54.210.26.138:8500
```

Cause a container to get created, e.g.
```
$ docker run -it --rm ubuntu:latest /bin/sh
```

# Environment

```
uname -a
Linux swarm-0 3.16.0-43-generic #58~14.04.1-Ubuntu SMP Mon Jun 22 10:21:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

```
docker version
Client:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   9d0eef5
 Built:        Thu Sep  3 20:40:56 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   9d0eef5
 Built:        Thu Sep  3 20:40:56 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true
```

```
docker info
Containers: 3
Images: 17
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 23
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-43-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 2
Total Memory: 7.304 GiB
Name: swarm-0
ID: SVSA:AXHN:GL2P:UEMI:3OE4:H2RL:U3BI:34WE:DNB3:G5OL:NXOH:I4VI
WARNING: No swap limit support
Labels:
 com.docker.network.driver.overlay.bind_interface=eth0
 provider=amazonec2
Experimental: true
```

### PR DESCRIPTION
**Pull request by aboch**
- incorrect handling during datastore write

Fixes #495 

Signed-off-by: Alessandro Boch <aboch@docker.com>

### CODE REVIEW

File: bitseq/sequence.go [hunk 1]
```diff
@@ -273,12 +272,9 @@ func (h *Handle) set(ordinal uint32, any bool, release bool) (uint32, error) {
 			continue
 		}
 
-		// Unless unexpected error, save private copy to local copy
+		// Previous atomic push was succesfull. Save private copy to local copy
 		h.Lock()
 		defer h.Unlock()
-		if h.dbIndex != ci {
-			return ret, fmt.Errorf("unexected database index change")
-		}
```
Comment (mavenugo) [inline bitseq/sequence.go]: As you are checking for h.dbIndex against ci, this should NOT have failed. But, the reason it failed is because of `watchForChanges` callback. But anyways, this is a wrong check and must go. So that is good.

But, can you also remove the `h.dbIndex = nh.dbIndex` in the following code ?
I dont want this to override a valid dbIndex update due to a remote operation.
Lets make sure that the dbIndex is updated only from the watch thread and make it consistent.

Comment (aboch) [inline bitseq/sequence.go]: Thanks. That makes me recollect the if check was meant to be against nh.Index (it was a paranoid check)

Right, there should be no need to copy the dbIndex, given h will get it updated by the watch

Comment (aboch) [inline bitseq/sequence.go]: As we discussed offline, when the local datastore comes since it does not support the watch we then need to store the index in h explicitly.

Comment (mavenugo) [inline bitseq/sequence.go]: That might be true. But I think it is a mistake to even have a `nh` as a copy. Instead, I think you should operate just on the primary handle `h` and maybe retain the `head` if you want to revert the `h.head` back to the old head (but still dont understand why you would want to do that). And call `h.writeToStore()` instead of `nh.writeToStore()`.

But, since the current issue is a basic breakage, i would be okay to go with the current fix.
We can certainly come back and fix this properly.

**Comment by mavenugo** [comment]
LGTM.

File: bitseq/sequence.go (hunk 1 above)
Comment (mrjana) [inline bitseq/sequence.go]: @mavenugo @aboch The reason why we make a copy and operate on that is because if two goroutines operate on the same h then what gets stored in the datastore will become inconsistent unless `h.Lock` is held for the entire duration of `set` function. That's why we need to work with a per-thread private copy of `h` and synchronize at the datastore with the help of `PutObjectAtomic`.

**Comment by mrjana** [comment]
LGTM

**Comment by mavenugo** [comment]
@aboch can you please push a vendor-in to docker asap ?
