### PR TITLE
Increase timeout in local store config

### LINKED ISSUE #1399: failed to update bridge store for object type *bridge.networkConfiguration: timeout
We seem to be getting this error _very_ frequently on our Jenkins CI server running docker 1.12 and docker-compose 1.8.

The error output is: 

```
Creating network "174d4e8b2cbaba7df674bcdd12b3606a_default" with the default driver
ERROR: failed to update bridge store for object type *bridge.networkConfiguration: timeout

  'up' failed with status 256: Creating network "174d4e8b2cbaba7df674bcdd12b3606a_default" with the default driver
```

The CI server is using docker-compose to stand up services and run tests that uses between 3 and 8 containers a new docker networnk for each test. There are 1-5 tests running concurrently for most of the workday.

I am slightly suspicious something isn't cleaning up after itself. With one test running there are a suspicious number of veths setup by docker:

`# docker ps | tail -n +2 | wc -l
7` 

4 of those containers are unrelated services.

`# ifconfig -a|grep veth | wc -l
49`

That seems high.

I'm at a loss as to how to recreate the issue without our exact environment. Please let me know if there is any more information I can provide to track down the problem.

Possibly related to issue #1374

### PR DESCRIPTION
**Pull request by aboch**
Fixes #1399
Related to https://github.com/docker/docker/issues/26251

### CODE REVIEW

File: datastore/datastore.go [hunk 1]
```diff
@@ -134,7 +135,8 @@ func makeDefaultScopes() map[string]*ScopeCfg {
 			Provider: string(store.BOLTDB),
 			Address:  defaultPrefix + "/local-kv.db",
 			Config: &store.Config{
-				Bucket: "libnetwork",
+				Bucket:            "libnetwork",
+				ConnectionTimeout: time.Minute,
```
Comment (sanimej) [inline datastore/datastore.go]: There is no one good number for timeouts. But in the earlier PR that @coolljt0725 pushed the timeout was set to 2 minutes. I am ok with 1 minute though if it was sufficient in the stress tests you did.

**Comment by sanimej** [comment]
LGTM

**Comment by coolljt0725** [comment]
this look good to me  :)
