### PR TITLE
Fix a panic in handling forwarded queries

### LINKED ISSUE #1117: panic in dns resolver: invalid memory address or nil pointer dereference
I just upgraded to Docker 1.11.0 and noticed that the docker daemon crashes when I run a suite of tests that do the following:

1. create a network
2. start several containers with above network
3. run some tests
4. tear down containers and network

Each tests is run in parallel.

After a few iterations, I can reliably get the Docker daemon to crash with the following panic:

```
time="2016-04-15T10:50:03.670207907-06:00" level=debug msg="client dns id 12960, changed id 23756"
time="2016-04-15T10:50:03.670386643-06:00" level=debug msg="Can't retrieve client context for dns id 23227"
time="2016-04-15T10:50:03.670445392-06:00" level=debug msg="Query node-1-5_ebaf3361161b41c796c6106de40d0e7e.example.com.[28] from 172.21.0.4:41501, forwarding to udp:128.222.208.98"
panic: runtime error: invalid memory address or nil pointer dereference         
[signal 0xb code=0x1 addr=0x30 pc=0x87d73d]                                     
                                                                                
goroutine 105572 [running]:                                                     
github.com/docker/libnetwork.(*resolver).forwardQueryStart(0xc82230d700, 0x0, 0x0, 0xc8225cc240, 0x0)
    /usr/src/docker/vendor/src/github.com/docker/libnetwork/resolver.go:442 +0x5d
github.com/docker/libnetwork.(*resolver).ServeDNS(0xc82230d700, 0x0, 0x0, 0xc8225cc240)
    /usr/src/docker/vendor/src/github.com/docker/libnetwork/resolver.go:391 +0xde4
github.com/miekg/dns.(*Server).serve(0xc820340dd0, 0x7fb230734f18, 0xc821b1cab0, 0x7fb230734fc0, 0xc82230d700, 0xc82099c400, 0x51, 0x200, 0xc820339d48, 0xc820d30e00, ...)
    /usr/src/docker/vendor/src/github.com/miekg/dns/server.go:535 +0x7c1        
created by github.com/miekg/dns.(*Server).serveUDP                              
    /usr/src/docker/vendor/src/github.com/miekg/dns/server.go:489 +0x3d5        
```

### PR DESCRIPTION
**Pull request by sanimej**
Fixes #1117 
Related to [docker/docker #22081] (https://github.com/docker/docker/issues/22081)

Signed-off-by: Santhosh Manohar <santhosh@docker.com>

### CODE REVIEW

File: resolver.go [hunk 1]
```diff
@@ -388,7 +391,7 @@ func (r *resolver) ServeDNS(w dns.ResponseWriter, query *dns.Msg) {
 
 			// forwardQueryStart stores required context to mux multiple client queries over
 			// one connection; and limits the number of outstanding concurrent queries.
-			if r.forwardQueryStart(w, query) == false {
+			if r.forwardQueryStart(w, query, queryID) == false {
```
Comment (mrjana) [inline resolver.go]: The passed `query` contains the ID. And queryID seems to initialized to `query.ID` above so I don't understand the need to pass it separately. What is it fixing?

Comment (sanimej) [inline resolver.go]: forwardQueryStart() changes the ID in the query to the one allocated by embedded Server. After sending the query to a first resolver if it timesout or gets a response but couldn't retrieve the context we continue and send it to the next resolver. When doing that the ID we have to save is the one that we got from the client and not the one in the current query because its the changed value.

**Comment by mavenugo** [comment]
LGTM

**Comment by mrjana** [comment]
LGTM
